security:
    encoders:
        FOS\UserBundle\Model\UserInterface: argon2i

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            guard:
                authenticators:
                    - 'App\Security\Guard\UcoAuthenticator'
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout: true
            anonymous: true

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login , role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/register/ , role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/$ , role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/ , role: ROLE_USER  }